myproject/boardgames/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

# from views import board_games_list

app_name = 'boardgames'
urlpatterns = [
    path('', views.board_games_list, name='home'),
    # path('boardgames/', include('boardgames.urls')),
    # path('accounts/', include('django.contrib.auth.urls')),
    path('index', views.board_games_list, name='index'),
    path('boardgame/<int:pk>/', views.detail, name='boardgame_detail'),
    path('signup/', views.signup, name='signup'),
    path('wishlist/', views.wishlist, name='wishlist'),
    path('library/', views.library, name='library'),
    path('boardgame/<int:pk>/add-to-library/', views.add_to_library, name='add_to_library'),
    path('boardgame/<int:pk>/add-to-wishlist/', views.add_to_wishlist, name='add_to_wishlist'),
    path('login/', views.login_view, name='login'),
    path('boardgame/<int:pk>/add-to-library/', views.add_to_library, name='add_to_library'),
    path('search/', views.search, name='search'),
    path('<int:pk>/recommendations/', views.recommendations, name='recommendations'),
    path('<int:game_id>/remove_from_wishlist/', views.remove_from_wishlist, name='remove_from_wishlist'),
    path('<int:game_id>/add_review/', views.add_review, name='add_review'),
    path('<int:game_id>/join_community/', views.join_community, name='join_community'),
    path('<int:pk>/', views.detail, name='detail'),
    path('detail/<int:pk>/', views.detail, name='detail'),
    path('clubs/', views.club_list, name='club_list'),
    # path('recommendations/', views.recommendations_user, name='recommendations_user'),
    path('recommendations/<int:user_id>/', views.recommendations_user, name='recommendations_user'),
    path('password-reset/', views.password_reset_request, name='password_reset'),
    path('password-reset/done/', views.PasswordResetDoneCustomView.as_view(), name='password_reset_done'),
    path('password-reset/confirm/<uidb64>/<token>/', views.PasswordResetConfirmCustomView.as_view(),
         name='password_reset_confirm'),
    path('password-reset/complete/', views.PasswordResetCompleteCustomView.as_view(), name='password_reset_complete'),
    path('<int:game_id>/add_review/', views.add_review, name='add_review'),
    path('<int:game_id>/join_community/', views.join_community, name='join_community'),
    path('join-club/', views.join_club, name='join_club'),
    # path('user-profile/', views.user_profile, name='user_profile'),
    path('user-profile/<int:user_id>/', views.user_profile, name='user_profile'),

]

myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('boardgames.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

myproject/boardgames/forms.py
from .models import UserProfile
from django import forms
from .models import Review, CommunityMember
from .models import Club

class SignUpForm(forms.ModelForm):
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.', initial='')
    username = forms.CharField(max_length=30, initial='')
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    IDENTITY_CHOICES = [
        ('player', 'Player'),
        ('game_dev', 'Game Developer'),
        ('club_mgr', 'Club Manager'),
        ('admin', 'Administrator'),
    ]
    identity = forms.ChoiceField(choices=IDENTITY_CHOICES, widget=forms.Select(attrs={'class': 'form-control form-control-sm'}), required=False)

    GENRE_CHOICES = [
        ('strategy', 'Strategy'),
        ('party', 'Party'),
        ('cooperative', 'Cooperative'),
        ('deck_building', 'Deck Building'),
        ('worker_placement', 'Worker Placement'),
        ('thematic', 'Thematic'),
    ]
    favorite_genre = forms.ChoiceField(choices=GENRE_CHOICES, widget=forms.Select(attrs={'class': 'form-control form-control-sm'}), required=False, initial='')
    class Meta:
        model = UserProfile
        fields = ('username', 'email', 'password1', 'password2', 'identity', 'favorite_genre')

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        user = super(SignUpForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user



class JoinClubForm(forms.Form):
    club = forms.ModelChoiceField(queryset=Club.objects.all())

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['rating', 'comment']

class JoinCommunityForm(forms.ModelForm):
    class Meta:
        model = CommunityMember
        fields = []

myproject/boardgames/views.py
from django.contrib.auth.models import User
from django.template.loader import render_to_string
from django.views.generic import ListView, DetailView
from .models import BoardGame, UserProfile, Wishlist, Library, Club
from .forms import SignUpForm
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect
from django.shortcuts import render
from django.contrib.auth import authenticate, login
from django.db.models import Q
from django.db.models import F
from django.contrib import messages
from django.shortcuts import render, redirect
from .models import BoardGame, Review, CommunityMember
from .forms import ReviewForm, JoinCommunityForm
from django.db import IntegrityError
from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse
from django.contrib.auth.tokens import default_token_generator
from django.utils.http import urlsafe_base64_encode
from django.utils.encoding import force_bytes


from django.shortcuts import render, redirect
from .models import Club
from .forms import JoinClubForm

def join_club(request):
    if request.method == 'POST':
        form = JoinClubForm(request.POST)
        if form.is_valid():
            club = form.cleaned_data['club']
            club_id = club.id

            user_profile = UserProfile.objects.get(username=request.user.username)
            user_profile.clubs.add(club_id)
            user_profile.save()
            return redirect('boardgames:club_list')
    else:
        form = JoinClubForm()

    return render(request, 'boardgames/join_club.html', {'form': form})


@login_required
def user_profile(request, user_id):
    # user = request.user
    user = get_object_or_404(UserProfile, id=user_id)
    library_items = Library.objects.filter(user=user)

    wishlist_items = Wishlist.objects.filter(user=user)

    communities = CommunityMember.objects.filter(user=user)

    reviews = Review.objects.filter(user=user)

    clubs = user.clubs.all()


    context = {
        'user': user,
        'library_items': library_items,
        'wishlist_items': wishlist_items,
        'communities': communities,
        'reviews': reviews,
        'clubs': clubs,
    }
    return render(request, 'boardgames/user_profile.html', context)

class BoardGameListView(ListView):
    model = BoardGame
    template_name = 'boardgames/board_games_list.html'
    context_object_name = 'boardgames'

@login_required
def remove_from_wishlist(request, game_id):
    try:
        board_game = BoardGame.objects.get(id=game_id)
        user_profile = request.user
        print(f"Removing {board_game.title} from the wishlist of {user_profile.username}")
        user_profile.wishlist.remove(board_game)
        user_profile.save()
        user_wishlist_item = Wishlist.objects.get(user=user_profile, game=board_game)
        user_wishlist_item.delete()
        messages.success(request, f"Removed {board_game.title} from your wishlist.")
    except BoardGame.DoesNotExist:

        messages.error(request, f"Board game with ID {game_id} does not exist.")
    except Exception as e:
        messages.error(request, f"Error: {e}")

    return redirect('boardgames:wishlist')

@login_required
def add_review(request, game_id):
    game = BoardGame.objects.get(pk=game_id)
    user_profile = request.user
    existing_review = Review.objects.filter(user=user_profile, game=game).first()

    if request.method == "POST":
        form = ReviewForm(request.POST, instance=existing_review)
        if form.is_valid():
            review = form.save(commit=False)
            review.user = user_profile
            review.game = game
            review.save()
            return redirect('boardgames:detail', pk=game.pk)

    else:
        form = ReviewForm(instance=existing_review)

    return render(request, "boardgames/add_review.html", {"form": form, "game_id": game_id})



@login_required
def join_community(request, game_id):
    game = BoardGame.objects.get(pk=game_id)
    community_members = CommunityMember.objects.filter(game=game)[:6]
    users = [member.user for member in community_members]

    if request.method == "POST":
        form = JoinCommunityForm(request.POST)
        if form.is_valid():
            community_member = form.save(commit=False)
            community_member.user = request.user
            community_member.game = game

            try:
                community_member.save()
                return redirect('boardgames:detail', pk=game.pk)
            except IntegrityError:
                form.add_error(None, "You have already joined this game community.")
    else:
        form = JoinCommunityForm()

    return render(request, "boardgames/join_community.html", {"form": form, "game_id": game_id, "users": users})

def club_list(request):
    clubs = Club.objects.all()
    return render(request, 'boardgames/club_list.html', {'clubs': clubs})
def detail(request, pk):
    boardgame = BoardGame.objects.get(pk=pk)
    reviews = Review.objects.filter(game=boardgame)
    community_members = CommunityMember.objects.filter(game=boardgame)

    context = {
        'boardgame': boardgame,
        'reviews': reviews,
        'community_members': community_members
    }
    return render(request, 'boardgames/detail.html', context)





def board_games_list(request):
    boardgames = BoardGame.objects.all()

    categories = set()
    for boardgame in boardgames:
        for category in boardgame.categories[2:-2].split("', '"):
            category = category.strip()
            if "," not in category:
                categories.add(category)
    games_limit = 20
    categorized_boardgames = {
        category: sorted(
            [boardgame for boardgame in boardgames if category in boardgame.categories[2:-2].split("', '")],
            key=lambda x: x.rating,
            reverse=True
        )[:games_limit]
        for category in categories
    }

    hot_games = BoardGame.objects.order_by('-rating')[:10]

    sorted_categories = sorted(categorized_boardgames, key=lambda x: len(categorized_boardgames[x]), reverse=True)
    sorted_categorized_boardgames = {category: categorized_boardgames[category] for category in sorted_categories}
    context = {
        'categorized_boardgames': sorted_categorized_boardgames,
        'hot_games': hot_games,
    }
    return render(request, 'boardgames/board_games_list.html', context)


    # return render(request, 'boardgames/board_games_list.html', {'categorized_boardgames': sorted_categorized_boardgames})

@login_required
def recommendations_user(request, user_id):
    user = request.user
    library = user.library_items.all()
    wishlist = user.wishlist_items.all()

    print("Library:", library)
    print("Wishlist:", wishlist)

    combined_games = [lib_item.game for lib_item in library] + [wish_item.game for wish_item in wishlist]
    recommendations = []
    for game in combined_games:
        game_recommendations = game.get_recommendations(library, wishlist)
        print(f"Recommendations for {game.title}: {game_recommendations}")
        recommendations.extend(game_recommendations)

    unique_recommendations = list(set(recommendations))[:10]
    print("Final Recommendations:", unique_recommendations)

    return render(request, 'boardgames/recommendations_user.html', {'recommended_games': unique_recommendations})




def recommendations(request, pk):
    boardgame = get_object_or_404(BoardGame, pk=pk)
    current_game_categories = set(boardgame.categories[2:-2].split("', '"))
    other_boardgames = BoardGame.objects.exclude(pk=pk)
    recommended_games = []
    for other_game in other_boardgames:
        other_game_categories = set(other_game.categories[2:-2].split("', '"))
        if current_game_categories.intersection(other_game_categories):
            recommended_games.append(other_game)
            if len(recommended_games) >= 10:
                break

    return render(request, 'boardgames/recommendations.html', {'boardgame': boardgame, 'recommended_games': recommended_games})



def search(request):
    query = request.GET.get('search_input')
    if query:
        results = BoardGame.objects.filter(
            Q(title__icontains=query) |
            Q(short_description__icontains=query) |
            Q(designers__icontains=query) |
            Q(artists__icontains=query) |
            Q(publishers__icontains=query)
        ).distinct()
    else:
        results = BoardGame.objects.none()

    return render(request, 'boardgames/search_results.html', {'results': results})



# def board_games_list(request):
#     boardgames = BoardGame.objects.all()
#
#     categories1 = set()
#     for boardgame in boardgames:
#         categories = boardgame.categories
#         categories= categories.replace("[","")
#         categories = categories.replace("]", "")
#         categories = categories.replace(" ", "")
#         categories = categories.replace("'", "")
#         categories = categories.split(",")
#         for category in categories:
#             categories1.add(category)
#     # print(categories1)
#
#     return render(request, 'boardgames/board_games_list.html', {'boardgames': boardgames, 'categories': sorted(categories)})


# def boardgame_detail(request, game_id):
#     boardgame = get_object_or_404(BoardGame, pk=game_id)
#     reviews = Review.objects.filter(game=boardgame)
#     community_comments = Community.objects.filter(game=boardgame)
#     guides = Guide.objects.filter(game=boardgame)
#
#     return render(request, 'boardgames/detail.html', {
#         'boardgame': boardgame,
#         'reviews': reviews,
#         'community_comments': community_comments,
#         # 'guides': guides,
#     })
def home(request):
    return render(request, 'boardgames/home.html')

myproject/boardgames/templates/boardgames/add_review.html
{% extends 'boardgames/base.html' %}

{% block content %}
<h1 class=custom-text-color>Add a Review</h1>
<form method="POST">
    {% csrf_token %}
    <div class="form-group">
        <label for="{{ form.rating.id_for_label }}" class="form-label text-white">Rating:</label>
        {{ form.rating }}
    </div>
    <div class="form-group">
        <label for="{{ form.comment.id_for_label }}" class="form-label text-white">Comment:</label>
        {{ form.comment }}
    </div>
    <button type="submit" class="btn btn-primary">Submit Review</button>
</form>
{% endblock %}

myproject/boardgames/templates/boardgames/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>



    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+Knujsl5/xMNZ6o5kPAAO3mUz7Wi3DfEDFOcXdSRiDh1z/u" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-eMNCOe7tC1doHpGoJtKh7z7lGz7fuP4F8nfdFvAOA6Gg/z6Y5J6XqqyGXYM2ntX5" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.min.js" integrity="sha384-cn7l7gDp0eyniUwwAZgrzD06kc/tftFf19TOAs2zVinnD/C7E91j9yyk5//jjpt/" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <style>
        body {
            background-color: #232023;
        }

        .navbar {
            background-color: #000000;
        }

        .navbar-brand {
            font-weight: bold;
            font-size: 24px;
        }
        .custom-text-color {
        color: #f8d17f;
        }

        .navbar img {
            margin-right: 10px;
        }

        .nav-link {
            color: #f8d17f;
            transition: color 0.3s;
        }

        .nav-link:hover {
            color: #fbe8bf;
            transition: color 0.3s;
        }

        .nav-link.active,
        .nav-link.disabled {
            color: #fff;
        }
        .btn-primary {
    background-color: #333333;
    border-color: #007bff;
  }

  .btn-primary:hover {
    background-color: #AB8000;
    border-color: #0062cc;
  }

  .btn-secondary {
    background-color: #6c757d;
    border-color: #6c757d;
  }
    </style>
    <title>GameShack</title>
</head>
<body>
{% load static %}
  {% if user.is_authenticated %}
    <nav class="navbar navbar-expand-lg">
        <div class="container">
            <a class="navbar-brand custom-text-color" href="{% url 'boardgames:home' %}">
                <img src="{% static 'logo.jpeg' %}" alt="Logo" height="80" width="100">


<!--                GameShack-->
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav me-auto">
                    <li class="nav-item">
                        <a class="nav-link {% if request.resolver_match.url_name == 'boardgames:home' %}active{% endif %}" href="{% url 'boardgames:home' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if request.resolver_match.url_name == 'boardgames:wishlist' %}active{% endif %}" href="{% url 'boardgames:wishlist' %}">Wishlist</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if request.resolver_match.url_name == 'boardgames:library' %}active{% endif %}" href="{% url 'boardgames:library' %}">Library</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if request.resolver_match.url_name == 'boardgames:recommendations_user' %}active{% endif %}" href="{% url 'boardgames:recommendations_user' user.id %}">Recommendations</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if request.resolver_match.url_name == 'boardgames:club_list' %}active{% endif %}" href="{% url                         'boardgames:club_list' %}">Clubs</a>
                    </li>
                    <li class="nav-item">
                    <a class="nav-link {% if request.resolver_match.url_name == 'boardgames:user_profile' %}active{% endif %}" href="{% url 'boardgames:user_profile' user.id%}">UserProfile</a>
                    </li>
                </ul>
                <form class="d-flex" role="search" action="{% url 'boardgames:search' %}" method="GET">
                    <input name="search_input" class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-light" type="submit">Search</button>
                </form>


                <p class="custom-text-color my-auto mx-3">Welcome, {{ user.username }}!</p>
                <a role="button" class="btn btn-primary" href="{% url 'logout' %}">Logout</a>
            </div>
        </div>
    </nav>
  {% else %}
    <nav class="navbar navbar-expand-lg">
        <div class="container">
            <a class="navbar-brand custom-text-color" href="{% url 'boardgames:home' %}">
                <img src="{% static 'logo.jpeg' %}" alt="Logo" height="80" width="100">
<!--                GameShack-->
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav me-auto">
                    <li class="nav-item">
                        <a class="nav-link {% if request.resolver_match.url_name == 'boardgames:home' %}active{% endif %}" href="{% url 'boardgames:home' %}">Home</a>
                    </li>
                </ul>
                <form class="d-flex" role="search" action="{% url 'boardgames:search' %}" method="GET">
                    <input name="search_input" class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-light" type="submit">Search</button>
                </form>
                <a role="button" class="btn btn-primary ms-2" href="{% url 'login' %}">Login</a>
                <a role="button" class="btn btn-primary ms-2" href="{% url 'boardgames:signup' %}">Sign up</a>
            </div>
        </div>
    </nav>
  {% endif %}

  <div class="container" style="margin-top: 20px">
    {% block content %}{% endblock %}
  </div>
</body>
</html>

myproject/boardgames/templates/boardgames/club_list.html
{% extends 'boardgames/base.html' %}

{% block content %}
<style>
    .club-container {
        background-color: rgba(0, 0, 0, 0.8);
        padding: 20px;
        margin-bottom: 30px;
        border-radius: 5px;
        display: flex;
        flex-direction: column;
        justify-content: space-between;
    }
    .club-name {
        font-size: 24px;
        font-weight: 600;
        color: #f8d17f;
    }
    .club-detail {
        color: #f8d17f;
    }
    .join-club-btn {
        position: absolute;
        top: 140px;
        right: 150px;
    }
</style>
    <h1 class="my-4 custom-text-color">Clubs</h1>
    <div class="container">
        <div class="d-flex justify-content-end">
            <a href="{% url 'boardgames:join_club' %}" class="btn btn-primary join-club-btn">Click to Join a Club</a>
        </div>
        {% for club in clubs %}
            <div class="club-container mb-4">
                <h2 class="club-name">{{ club.name }}</h2>
                <p class="club-detail">Website: <a href="{{ club.link }}" target="_blank">{{ club.link }}</a></p>
                <p class="club-detail">Contact: {{ club.contact }}</p>
                <p class="club-detail">Address: {{ club.address }}, {{ club.city }}</p>
            </div>
        {% empty %}
            <p class="custom-text-color">No clubs found.</p>
        {% endfor %}
    </div>
{% endblock %}

myproject/boardgames/templates/boardgames/password_reset.html
{% extends 'boardgames/base.html' %}

{% block content %}

  <h2 class="text-white">Password Reset Request</h2>
  <p class="text-white">Enter your email address below, and we'll send you instructions to reset your password.</p>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Send Password Reset Email</button>
  </form>
{% endblock %}

myproject/boardgames/templates/boardgames/wishlist.html
{% extends 'boardgames/base.html' %}

{% block content %}

<style>
  .card:hover {
    background-color: #3E3D53;
    transition: background-color 0.3s;
  }
  .card {
    background-color: rgba(0, 0, 0, 0.8);
  }
  .card-title {
    color: #D4D4D4;
  }
  .card-text {
    color: #D4D4D4;
  }
  .btn-secondary:hover {
    background-color: #3E3D53;
    border-color: #3E3D53;
  }
  .card-body {
    display: flex;
    flex-direction: column;
    justify-content: space-between;
  }
  .recommended-game-details {
    display: inline-block;
    margin-top: 10px;
    color: #007bff;
    text-decoration: none;
    margin-top: auto;
    text-align: center;
  }
  .recommended-game-details:hover {
    text-decoration: underline;
  }
  .recommended-game {
    background-color: rgba(0, 0, 0, 0.8);
    border-radius: 5px;
    padding: 15px;
    margin-bottom: 30px;
    width: 300px;
    display: flex;
    flex-direction: column;
    justify-content: space-between;
    transition: background-color 0.3s;
  }
  .recommended-game:hover {
    background-color: #3E3D53;
  }
  .recommended-game img {
    width: 100%;
    height: 200px;
    object-fit: cover;
    border-radius: 5px;
  }
  .recommendations-container {
    display: flex;
    flex-wrap: wrap;
    justify-content: space-around;
    margin-bottom: 30px;
    width: 100%;
  }
</style>
<h1 class="my-4 custom-text-color">My Wishlist</h1>
<div class="recommendations-container">
  {% for boardgame in wishlist %}
  <div class="recommended-game">
    <div class="card" style="width: 270px; height: 450px;">
      <div class="card-img-container d-flex align-items-center justify-content-center" style="height: 200px; overflow: hidden;">
        <img src="{{boardgame.image_url}}" class="card-img-fluid" alt="Image cannot be loaded">
      </div>
      <div class="card-body">
        <h5 class="card-title text-center">{{ boardgame.title }}</h5>
        {% load wishList %}
        {% if boardgame.commerce_links|wishList == "No" %}
          <p class="card-text text-center mb-0"><b>Status: </b>Not Avaliable</p>
        <div class="mt-3 d-flex justify-content-center">
          <a class="recommended-game-details" href="{% url 'boardgames:boardgame_detail' boardgame.pk %}">View Details</a>
<!--            <a href="{% url 'boardgames:boardgame_detail' boardgame.pk %}" class="btn btn-primary me-2">View Details</a>-->
          </div>
        <a href="{% url 'boardgames:remove_from_wishlist' game_id=boardgame.id %}" class="btn btn-danger me-2">Remove</a>

        {% else %}
          {% with boardgame.commerce_links|wishList as list %}
          <p class="card-text text-center mb-0"><b>Status:</b> {{ list.2 }}</p>
          <p class="card-text text-center mb-0"><b>Sale Price:</b> {{ list.4 }}</p>
          <p class="card-text text-center mb-0"><b>Regular Price:</b> {{ list.6 }}</p>
          {% endwith %}
          <div class="mt-3 d-flex justify-content-center">
            <a class="recommended-game-details" href="{% url 'boardgames:boardgame_detail' boardgame.pk %}">View Details</a>
<!--            <a href="{% url 'boardgames:boardgame_detail' boardgame.pk %}" class="btn btn-primary me-2">View Details</a>-->
          </div>
          <div class="mt-3 d-flex justify-content-center">
            <a href="{% url 'boardgames:remove_from_wishlist' game_id=boardgame.id %}" class="btn btn-danger me-2">Remove</a>
            {% load wishList %}
            {% with boardgame.commerce_links|wishList as list %}
            <a href="{{ list.0 }}" class="btn btn-success{% if not list.0 %} disabled{% endif %}">Buy Now</a>
            {% endwith %}
          </div>
        {% endif %}
      </div>
    </div>
  </div>
  {% empty %}
  <div class="col-md-6 col-lg-4 mb-4">
    <div class="card">
      <div class="card-body">
        <p class="card-text">No games in your wishlist yet.</p>
      </div>
    </div>
  </div>
  {% endfor %}
</div>
<button type="button" class="btn btn-secondary mt-4" onclick="goBack()">Go Back</button>

<script>
  function goBack() {
    window.history.back();
  }
  document.getElementById("wishlist").className = "nav-link active";
</script>

{% endblock %}